import type { Metadata } from "next";
import "./globals.css";
import { GameProvider } from "./context/GameContext";
import ToastProvider from "./components/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GameProvider>
      <html lang="en">
        <body>
          <ToastProvider>{children}</ToastProvider>
        </body>
      </html>
    </GameProvider>
  );
}
